name: Pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          export PYTHONPATH=$PYTHONPATH:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pytest
      - name: Analysing the code with pylint
        run: |
          pylint $(find . -path "./src/*" -name "*.py" | xargs) --disable=missing-docstring,unused-wildcard-import,no-value-for-parameter,import-error,broad-except,redundant-keyword-arg,too-few-public-methods
          pytest  $(find . -path "./src/unit_tests.py")
